# -*- coding: utf-8 -*-
"""Capstone Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJSRtwmuvoJ15n8_qouiWPaLcyky4NYM

## ***Generating Segmentation Masks from Mask2Former (ADE20K)***

# ***Pratiksha Kumari***
# ***IITMCS_24061017***
"""

# -------------------------
# 1. Setup & Installs
# -------------------------

pip install --upgrade pip setuptools wheel
pip install 'git+https://github.com/facebookresearch/detectron2.git'
pip install timm fvcore iopath pycocotools matplotlib
pip install transformers
pip install evaluate

# -------------------------
# 2. Imports & Config
# -------------------------
import os
import random
import numpy as np
from PIL import Image
import torch
import matplotlib.pyplot as plt
from tqdm import tqdm

from transformers import AutoImageProcessor, Mask2FormerForUniversalSegmentation
import evaluate

# -------------------------
# 3. Reproducibility
# -------------------------
seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# -------------------------
# 4. Dataset Preparation
# -------------------------
os.makedirs("datasets", exist_ok=True)
!wget -P datasets http://data.csail.mit.edu/places/ADEchallenge/ADEChallengeData2016.zip
!unzip -q datasets/ADEChallengeData2016.zip -d datasets/

# Define validation images and masks
val_dir = "datasets/ADEChallengeData2016/images/validation"
mask_dir = "datasets/ADEChallengeData2016/annotations/validation"

val_images = sorted([os.path.join(val_dir, f) for f in os.listdir(val_dir) if f.endswith(".jpg")])
val_masks = sorted([os.path.join(mask_dir, f) for f in os.listdir(mask_dir) if f.endswith(".png")])

# -------------------------
# 5. Model Setup
# -------------------------
processor = AutoImageProcessor.from_pretrained(
    "facebook/mask2former-swin-large-ade-semantic"
)
model = Mask2FormerForUniversalSegmentation.from_pretrained(
    "facebook/mask2former-swin-large-ade-semantic"
)
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

# -------------------------
# 6. Single Image Inference & Visualization
# -------------------------
def visualize_single_image(img_path):
    image = Image.open(img_path).convert("RGB")
    inputs = processor(images=image, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    seg_map = processor.post_process_semantic_segmentation(
        outputs, target_sizes=[image.size[::-1]]
    )[0].cpu().numpy()

    plt.figure(figsize=(12,5))
    plt.subplot(1,2,1)
    plt.imshow(image)
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(seg_map, cmap="nipy_spectral")
    plt.title("Predicted Mask")
    plt.axis("off")
    plt.show()

# Test with one image
visualize_single_image(val_images[0])

# -------------------------
# 7. Evaluation on Multiple Images
# -------------------------
metric = evaluate.load("mean_iou")

for img_path, gt_path in tqdm(zip(val_images[:500], val_masks[:500]), total=500):
    # Load and preprocess image
    image = Image.open(img_path).convert("RGB")
    inputs = processor(images=image, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    seg_map = processor.post_process_semantic_segmentation(
        outputs, target_sizes=[image.size[::-1]]
    )[0].cpu().numpy()

    # Ground truth processing
    gt_mask = np.array(Image.open(gt_path))
    gt_mask_corrected = np.where(gt_mask == 0, 255, gt_mask - 1).astype(np.uint8)
    gt_mask_resized = np.array(Image.fromarray(gt_mask_corrected).resize(
        (seg_map.shape[1], seg_map.shape[0]), Image.NEAREST
    ))

    metric.add_batch(predictions=[seg_map], references=[gt_mask_resized])

results = metric.compute(num_labels=150, ignore_index=255, reduce_labels=False)
print("✅ Multi-class Evaluation Results on 500 images:")
print("Mean IoU:", results["mean_iou"])
print("Mean Accuracy:", results["mean_accuracy"])

# -------------------------
# 8. Visualize Random Samples
# -------------------------
sample_indices = random.sample(range(len(val_images)), 10)

for idx in sample_indices:
    img_path = val_images[idx]
    gt_path = val_masks[idx]

    image = Image.open(img_path).convert("RGB")
    inputs = processor(images=image, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    seg_map = processor.post_process_semantic_segmentation(
        outputs, target_sizes=[image.size[::-1]]
    )[0].cpu().numpy()

    gt_mask = np.array(Image.open(gt_path))
    gt_mask_corrected = np.where(gt_mask == 0, 255, gt_mask - 1).astype(np.uint8)
    gt_mask_resized = np.array(Image.fromarray(gt_mask_corrected).resize(
        (seg_map.shape[1], seg_map.shape[0]), Image.NEAREST
    ))

    plt.figure(figsize=(15,5))
    plt.subplot(1,3,1)
    plt.imshow(image)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(gt_mask_resized, cmap="nipy_spectral")
    plt.title("Ground Truth Mask")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(seg_map, cmap="nipy_spectral")
    plt.title("Predicted Mask")
    plt.axis("off")
    plt.show()

# -------------------------
# 9. Conclusion
# -------------------------
print("""
✅ Project Complete: Semantic Segmentation with Mask2Former (Swin-Base) on ADE20K
- Evaluated 500 validation images
- Mean IoU: ~0.46
- Mean Accuracy: ~0.63
- Model performs well on large/common objects; struggles with small/rare objects
- Pretrained model provides strong baseline without fine-tuning
""")
